/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCheckoutsRouteImport } from './routes/app.checkouts'
import { Route as AppFailedPaymentsRouteImport } from './routes/app.failed-payments'
import { Route as AppReceivablesRouteImport } from './routes/app.receivables'
import { Route as AppRecoveryRouteImport } from './routes/app.recovery'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutsRoute = AppCheckoutsRouteImport.update({
  id: '/checkouts',
  path: '/checkouts',
  getParentRoute: () => AppRoute,
} as any)
const AppFailedPaymentsRoute = AppFailedPaymentsRouteImport.update({
  id: '/failed-payments',
  path: '/failed-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRoute = AppRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/failed-payments': typeof AppFailedPaymentsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/failed-payments': typeof AppFailedPaymentsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/failed-payments': typeof AppFailedPaymentsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/recovery': typeof AppRecoveryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/checkouts'
    | '/app/failed-payments'
    | '/app/receivables'
    | '/app/recovery'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/analytics'
    | '/app/checkouts'
    | '/app/failed-payments'
    | '/app/receivables'
    | '/app/recovery'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/checkouts'
    | '/app/failed-payments'
    | '/app/receivables'
    | '/app/recovery'
    | '/app/settings'
    | '/app/subscriptions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkouts': {
      id: '/app/checkouts'
      path: '/checkouts'
      fullPath: '/app/checkouts'
      preLoaderRoute: typeof AppCheckoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/failed-payments': {
      id: '/app/failed-payments'
      path: '/failed-payments'
      fullPath: '/app/failed-payments'
      preLoaderRoute: typeof AppFailedPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receivables': {
      id: '/app/receivables'
      path: '/receivables'
      fullPath: '/app/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recovery': {
      id: '/app/recovery'
      path: '/recovery'
      fullPath: '/app/recovery'
      preLoaderRoute: typeof AppRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCheckoutsRoute: typeof AppCheckoutsRoute
  AppFailedPaymentsRoute: typeof AppFailedPaymentsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppRecoveryRoute: typeof AppRecoveryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCheckoutsRoute: AppCheckoutsRoute,
  AppFailedPaymentsRoute: AppFailedPaymentsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppRecoveryRoute: AppRecoveryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
